### ISSUE TITLE
Getting ERROR while Installing 

### ISSUE THREAD

**Issue by ashish-singh-bora** [HalilDeniz/MacMaster#5]
I was Installing this MacMaster But it showed me this ERROR.
BTW I'm using kali with XFCE desktop environment.

`$ python setup.py install
Traceback (most recent call last):
  File "/home/love/MacMaster/setup.py", line 9, in <module>
    long_description=open('README.md').read(),
                     ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
![Screenshot_2023-12-23_02-07-38](https://github.com/HalilDeniz/MacMaster/assets/135435891/edccedfb-4f8a-4d56-bbea-4ee759d83490)

**Comment by ashish-singh-bora** [comment]
Actually after reading setup.py program, I founded that the file name was wrong declared! So this issue is fixed NOW!!!

**Comment by HalilDeniz** [comment]
Setup.py file in the README.MD Can you write file as in the folder and replace it?
