### ISSUE TITLE
Remove prefix for tag

### ISSUE THREAD

**Issue by fabaff** [HalilDeniz/MacMaster#7]
It looks wired that the tags are prefixed with with [`MacChanger`](https://github.com/HalilDeniz/MacMaster/releases/tag/MacChanger-v1.3.0) while the project is called `MacMaster`.

Please update or remove the prefix from the tags. This make the life of the package maintainers easier :wink:

**Comment by HalilDeniz** [comment]
can you send me any screenshot

**Comment by fabaff** [comment]
![Screenshot from 2024-01-06 11-48-42](https://github.com/HalilDeniz/MacMaster/assets/116184/b11940a5-f06a-4d9c-8ea8-201b8530235e)
